version: '3.1'

services:

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: test_db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'admin'
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
